name: Azure Static Web App Deploy

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed] # Added 'closed' to trigger cleanup
    branches:
      - master

jobs:
  build-and-deploy:
    if: github.event_name != 'pull_request' || github.event.action != 'closed' # Avoid running on PR close
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use a compatible Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/" # Path to your Angular app source code
          output_location: "dist/silver-catalog" # Path to the built Angular app

  close-pull-request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup Staging Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
