name: Release Workflow

on:
  push:
    branches:
      - "master"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    if: ${{ !startsWith(github.ref, 'refs/heads/master') && !startsWith(github.ref, 'refs/heads/release') }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Complete Status Check
        if: always()
        run: |
          echo "Setting status to 'success' for Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
